#!/usr/bin/env bash

# This script must be run within the ClojureScript top-level project
# directory.

set -ex

cd `dirname $0`/..

POM_TEMPLATE="pom.template.xml"
POM_FILE="pom.xml"

VERSION="1.0.0"
TAG=v$VERSION

sed -e s/CLOJURESCRIPT_VERSION/$VERSION/ < "$POM_TEMPLATE" > "$POM_FILE"

COMP_FILE=`mktemp /tmp/compiler.clj.XXXXXXXXXXX`
sed -e 's/^.def ^:dynamic \*clojurescript-version\*.*$/(def ^:dynamic *clojurescript-version* {:major 1, :minor 0, :incremental 0, :qualifier nil})/' src/clj/cljs/util.clj > $COMP_FILE
mv $COMP_FILE src/clj/cljs/util.clj

CLJS_FILE=`mktemp /tmp/core.cljs.XXXXXXXXXXX`
sed -e 's/^.def \*clojurescript-version\*.*$/(def *clojurescript-version* '\""1.0.0"\"')/' src/cljs/cljs/core.cljs > $CLJS_FILE
mv $CLJS_FILE src/cljs/cljs/core.cljs

if [ "$CLOJARS" = "true" ]; then
  echo "Creating tag $TAG"
  git tag -f "$TAG"
  echo "Cleaning and building"
  mvn clean package
  echo "Deploying to Clojars"
  mvn deploy:deploy-file \
      -DpomFile=$POM_FILE \
      -Dfile="target/clojurescript-${VERSION}.jar" \
      -DrepositoryId=clojars \
      -Durl="https://clojars.org/repo"
  echo "Pushing tag ${TAG} to GitHub"
  git push origin "$TAG"
else
  echo "Skipping Clojars deployment"
  mvn clean install
fi
